### ISSUE TITLE
Capslock  ENUMKEY_del issue?

### ISSUE THREAD

**Issue by HyruleanHero** [clc/chorder#2]
I have noticed that while in the *lock modes you cannot send the backspace through.

**Comment by priestdo** [comment]
Odd. That is not the case for me.
If I press caps lock (f xxxx) or number lock (n xxxx) then type some
letters or numbers, I can press backspace (f -x--) and it works as expected
deleting the char. and staying in the locked mode.

What behavior are you experiencing?

-Greg

**Comment by HyruleanHero** [comment]
Oh! I apologize, it was the Enter/Return key!
Sorry my mind thought one thing and my fingers typed another.

**Comment by priestdo** [comment]
Again, I am not seeing that issue.  Pressing far thumb and pinky together
gives [ENTER] key in both caps lock and num lock mode.  I don't know why
that would not work for you.

So, if I understand you, [ENTER] works as expected when typing text, but if
you have entered cap-lock (far thumb and all 4 fingers) or num-lock (near
thumb and all four fingers) it does not work.  When you leave caps-lock or
num-lock it returns to working?  Is that correct? If not please tell me how
I have miss-understood.

Please connect your chorder over the usb cable to the host with arduino ide
on it.  Open the serial monitor so you can see the serial output from the
FeatherChorder as it runs.  Connect the FeatherChorder over BLE to your
device.  Now when you type you should see what the FeatherChorder is trying
to send.  When you press the "F-- ---P" you should see in the serial
monitor window:

AT+BLEKEYBOARDCODE=0-00-28

AT+BLEKEYBOARDCODE=00-00

If you do, then your chorder is trying to do the right thing and the issue
may be on the receiving end.  If you see something else, let me know what
it is. If you do see the above lines in the monitor window,  please try
pariing with a different BT host.  It may be some configuration on the
device you are connecting with.

Other thoughts:

Have you made any modifications to the default ChordMappings.h?  If you
have, please try flashing your feather with the default files and see if it
does work.  In fact, it might be a good thing to just reflash anyway, and
see if that changes anything.

Any chance there is a wiring issue?  (the Monitor window may also give you
help figuring that out as well.

Does [ENTER] work if directly preceded by shift (Far thumb alone) or
num-shift (near thumb alone)?

For me, I get the desired result (an [ENTER] keypress) in plain text, if
preceded by num-shift or shift or both, when in caps-lock, num-lock or
both.

The only place "F-- ---P" is not mapped to "ENUMKEY_enter" is in the
function key mapping.

Please let me know what you figure out.

Greg

**Comment by HyruleanHero** [comment]
3rd time is the charm, okay so it wasn't [ENTER] or [BACKSPACE],
It was the [DELETE] "F-- -MR-" all along! It only occurs when the caps lock is active.
I feel a little silly for not tracking this down more efficiently. Sorry about all of that unnecessary work you did, but I do very much appreciate the troubleshooting tips that you graciously replied with.

**Comment by priestdo** [comment]
I am sorry you are having problems, but
I am not able to reproduce your issue(s).

Were you able to connect your featherchorder to a different device to see
if it was device specific?

Were you able to look at the serial monitor?

If your problems persist, please include serial monitor output (as
suggested in my last message) and annotate it with some comments about what
you were pressing when.  Also, how about a closeup  picture of your
feather?  Given your ongoing issues, I would like to visually confirm your
wiring.

But before that, just to be sure, please grab a copy of the latest version
of the FeatherChorder and reflash your feather.

Again, if you can give me more to work with I will revisit your issue,

-Greg

**Comment by HyruleanHero** [comment]
This turned out to be the incompetent ramblings of a novice. It sends the delete through text just needs to be selected first. I'll close this issue and learn how to use the serial monitor.
Thanks again for all your time and energy! keep up the good work!
